### ISSUE TITLE
Errors if entry title is missing

### ISSUE THREAD

**Issue by msschwartz21** [johndoe31415/biblint#2]
When I tried to run biblint on a file where many entries were missing titles, it threw an error instead of flagging the missing titles as an issue.
```
Traceback (most recent call last):
  File "biblint", line 127, in <module>
    for complaint in checker.check_all():
  File "/Users/morganschwartz/Code/biblint/BibLintChecks.py", line 294, in check_all
    indices_by_title = BibliographyTools.get_indices_by_title(self.bibliography)
  File "/Users/morganschwartz/Code/biblint/Tools.py", line 86, in get_indices_by_title
    title = BibEntryTools.readable_title(entry)
  File "/Users/morganschwartz/Code/biblint/Tools.py", line 75, in readable_title
    title = bibentry.rawtext("title")
  File "/Users/morganschwartz/Code/biblint/BibEntry.py", line 158, in rawtext
    return "".join(field.text for field in self.parsefield(fieldname))
  File "/Users/morganschwartz/Code/biblint/BibEntry.py", line 154, in parsefield
    parsedtext = self.parsetext(self[fieldname])
  File "/Users/morganschwartz/Code/biblint/BibEntry.py", line 216, in __getitem__
    return self._properties[key]
KeyError: 'title'
```

**Comment by johndoe31415** [comment]
Yeah, that shouldn't happen... let me fix this one tonight as well, good catch.
